In [1]:
import tensorflow as tf

/home/rodrigo/Documents/Rodrigo/Python_VE/tf_1_3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/rodrigo/Documents/Rodrigo/Python_VE/tf_1_3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/rodrigo/Documents/Rodrigo/Python_VE/tf_1_3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/hom

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World ")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World '


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)


In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [18]:
const = tf.constat(10)


AttributeError: module 'tensorflow' has no attribute 'constat'

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrand = tf.random_normal((4,4),mean=0,stddev=1.0)

In [24]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
my_ops = [const,fill_mat,myzeros,myones,myrand,myrandu]

In [26]:
sess = tf.InteractiveSession()

In [29]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.006405    0.03594793  0.3231633  -0.04998918]
 [ 0.47940084 -1.6492379  -0.33522743  0.65948266]
 [-0.25426468  0.54568845  0.64824104 -0.14912696]
 [ 0.5645038   0.02403666 -2.3354735   0.58704704]]


[[0.90818095 0.87420917 0.59841454 0.9190477 ]
 [0.800037   0.15073419 0.76427376 0.7113296 ]
 [0.60343075 0.30243814 0.8916789  0.34714723]
 [0.7070712  0.89614224 0.27566528 0.9385873 ]]




In [30]:
a = tf.constant([[1,2],[3,4]])

In [31]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [33]:
b = tf.constant([[10],[100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a,b)

In [37]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [39]:
result.eval()

array([[210],
       [430]], dtype=int32)